[package]
name = "aoc-24-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
lazy_static = "1.5.0"
num-integer = "0.1.46"
regex = "1.11.1"
strum = "0.27.1"
strum_macros = "0.27.1"
test-case = "3.3.1"
